### ISSUE TITLE
Seems to just not work?

### ISSUE THREAD

**Issue by pollysee** [gapop/pinboard-webextension#13]
The top three buttons (Save to pinboard, read later, and save tab set) do nothing when clicked. The other two buttons open the expected page on pinboard. Preferences opens the options. Maybe I'm missing something? I am logged into pinboard. This is on firefox 132 on windows.

**Comment by gapop** [comment]
I cannot reproduce this at all. I have tested in Firefox 132.0.2 on Windows 10 with the latest updates (the only Windows to which I have access) with an older profile and also after a Firefox reset / "refresh". I've tested with Firefox Nightly as well. Both the toolbar button menu and the context menu worked for me.

I'm not sure what to recommend, because I don't know what may cause this behavior, but you could try testing in a new Firefox profile, to make sure there's no settings/extension interference. For this, run `firefox -ProfileManager` from Win+R and create a new profile. Or try installing an older version of the extension from [AMO](https://addons.mozilla.org/en-US/firefox/addon/pinboard-webextension/versions/), like 1.50.

**Comment by pollysee** [comment]
OK, thanks for replying. I tried on a new Firefox profile and it works, so this is clearly on my end. Thanks!
